version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    ports:
     - "0.0.0.0:2181:2181"
     - "0.0.0.0:2888:2888"
     - "0.0.0.0:3888:3888"
  kafka:
    image: quay.io/debezium/kafka:2.3
    ports:
     - "0.0.0.0:9092:9092"
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - "0.0.0.0:1433:1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
  connect:
    image: quay.io/debezium/connect:2.3
    ports:
     - "0.0.0.0:8083:8083"
    links:
     - kafka
     - sqlserver
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
